// YAMNet 이름표 한국어 — 소리 가르치기(sound.html) 전용.
//
// YAMNet 은 521가지 소리 이름을 영어로만 갖고 있다 (모델 파일 안 yamnet_label_list.txt).
// 교실에서 자주 나오는 것만 옮겼다. 없는 이름은 영어 그대로 보여 준다 — 아이가
// "AI 가 원래 아는 말" 이 따로 있다는 것을 보는 것도 배울 거리라서 억지로 다 옮기지 않았다.
// 열쇠는 모델이 내놓는 categoryName 과 글자 하나까지 같아야 한다.

export const KO = {
  'Speech': '말소리',
  'Child speech, kid speaking': '아이 말소리',
  'Conversation': '대화',
  'Narration, monologue': '혼잣말',
  'Babbling': '옹알이',
  'Speech synthesizer': '컴퓨터 목소리',
  'Shout': '외침',
  'Yell': '고함',
  'Whispering': '속삭임',
  'Laughter': '웃음소리',
  'Baby laughter': '아기 웃음',
  'Giggle': '킥킥 웃음',
  'Crying, sobbing': '울음',
  'Baby cry, infant cry': '아기 울음',
  'Singing': '노래',
  'Humming': '흥얼거림',
  'Whistling': '휘파람',
  'Breathing': '숨소리',
  'Cough': '기침',
  'Sneeze': '재채기',
  'Sniff': '훌쩍임',
  'Walk, footsteps': '발소리',
  'Chewing, mastication': '씹는 소리',
  'Hands': '손 소리',
  'Finger snapping': '손가락 튕기기',
  'Clapping': '박수',
  'Cheering': '환호',
  'Applause': '박수갈채',
  'Chatter': '웅성웅성',
  'Crowd': '사람들 소리',
  'Children playing': '아이들 노는 소리',
  'Animal': '동물',
  'Dog': '개',
  'Bark': '멍멍',
  'Cat': '고양이',
  'Meow': '야옹',
  'Bird': '새',
  'Music': '음악',
  'Musical instrument': '악기',
  'Guitar': '기타',
  'Keyboard (musical)': '건반 악기',
  'Piano': '피아노',
  'Drum': '북',
  'Violin, fiddle': '바이올린',
  'Flute': '플루트',
  'Bell': '종',
  'Wind': '바람',
  'Water': '물',
  'Rain': '비',
  'Vehicle': '탈것',
  'Car': '자동차',
  'Door': '문',
  'Knock': '똑똑 (노크)',
  'Tap': '톡톡',
  'Squeak': '끽 소리',
  'Keys jangling': '열쇠 짤랑',
  'Scissors': '가위',
  'Typing': '타자 소리',
  'Computer keyboard': '컴퓨터 자판',
  'Writing': '글씨 쓰는 소리',
  'Alarm': '알람',
  'Telephone': '전화',
  'Ringtone': '벨소리',
  'Siren': '사이렌',
  'Whistle': '호루라기',
  'Clock': '시계',
  'Tick': '똑딱',
  'Tick-tock': '째깍째깍',
  'Glass': '유리',
  'Thump, thud': '쿵',
  'Bang': '쾅',
  'Slap, smack': '찰싹',
  'Beep, bleep': '삐 소리',
  'Silence': '조용함',
  'Sine wave': '삐― (한 음)',
  'Noise': '잡음',
  'White noise': '쏴― 잡음',
  'Inside, small room': '작은 방 안',
  'Inside, large room or hall': '넓은 방 안',
  'Television': '텔레비전',
  'Radio': '라디오',
};

// 화면에 보일 이름 — 한국어 화면이면 "박수", 영어 화면이면 모델 이름 그대로
export function labelOf(name, lang) {
  if (!name) return '?';
  return lang === 'ko' && KO[name] ? KO[name] : name;
}
